<?xml version="1.0"?>
<robot name="robot_chassis" xmlns:xacro="http://ros.org/wiki/xacro">
    
    <xacro:include filename="$(find my_ros_robot_description)/urdf/properties.xacro"/>

    <xacro:macro name="chassis" params="">
        <link name="base_footprint"/>
        
        <joint name="base_footprint_to_base_link" type="fixed">
            <parent link="base_footprint"/>
            <child link="base_link"/>
            <origin rpy="0.0 0.0 0.0" xyz="0.0 0.0 0.1"/>
            
        </joint>
        
        <link name="base_link">
        <collision>
                <origin rpy="0.0 0.0 0.0" xyz="-0.1 0.0 0.05" />
                <geometry>
                    <box size="0.6 ${WHEEL_SEPARATION-0.02} 0.15"/>
                </geometry>
            </collision>
        <inertial>
            <origin xyz="${CHASSIS_COM}" rpy="-0.1 0.0 0.05"/>
            <mass value="${CHASSIS_M}"/>
            <inertia ixx="${CHASSIS_Ixx}" ixy="${CHASSIS_Ixy}" ixz="${CHASSIS_Ixz}" iyy="${CHASSIS_Iyy}" iyz="${CHASSIS_Iyz}" izz="${CHASSIS_Izz}"/>
        </inertial>
            <visual>
                <origin rpy="0.0 0.0 0.0" xyz="-0.1 0.0 0.05" />
                <geometry>
                    <box size="0.6 ${WHEEL_SEPARATION-0.02} 0.15"/>
                </geometry>
            </visual>
            
        </link>

        <joint name="base_link_to_caster" type="fixed">
            <parent link="base_link"/>
            <child link="caster"/>
            <origin rpy="0.0 0.0 0.0" xyz="-0.3 0.0 -0.05"/>
        </joint>
        <link name="caster">
            <visual>
                <origin rpy="0.0 0.0 0.0" xyz="0 0.0 0.0" />
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </visual>
            <collision>
                <origin rpy="0.0 0.0 0.0" xyz="0 0.0 0.0" />
                <geometry>
                    <sphere radius="0.05"/>
                </geometry>
            </collision>
       
        </link>
         <gazebo reference = "base_link">
            <mu1>0.5</mu1>
            <mu2>0.5</mu2>
            <material>Gazebo/Black</material>
        </gazebo>

        <gazebo reference = "caster">
            <mu1>0.5</mu1>
            <mu2>0.5</mu2>
        </gazebo>
    </xacro:macro>
</robot>
